
name: Build APK
on: [repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update to 20%
        run: curl -s -X POST https://api.telegram.org/bot8876597863:AAE3A99UKha71_6X1hpJyZe8ySbTJkbLg_s/editMessageText -d chat_id=${{ github.event.client_payload.cid }} -d message_id=${{ github.event.client_payload.mid }} -d text="🔨 পরিবেশ সেটআপ হচ্ছে... [██░░░░░░░░] 20%"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
      
      - name: Update to 60%
        run: curl -s -X POST https://api.telegram.org/bot8876597863:AAE3A99UKha71_6X1hpJyZe8ySbTJkbLg_s/editMessageText -d chat_id=${{ github.event.client_payload.cid }} -d message_id=${{ github.event.client_payload.mid }} -d text="🔨 APK বিল্ড হচ্ছে... [██████░░░░] 60%"

      - run: flutter build apk --release

      - name: Update to 100%
        run: curl -s -X POST https://api.telegram.org/bot8876597863:AAE3A99UKha71_6X1hpJyZe8ySbTJkbLg_s/editMessageText -d chat_id=${{ github.event.client_payload.cid }} -d message_id=${{ github.event.client_payload.mid }} -d text="✅ বিল্ড সম্পন্ন! ফাইল পাঠানো হচ্ছে... [██████████] 100%"

      - name: Send APK
        run: curl -F chat_id='${{ github.event.client_payload.cid }}' -F document=@build/app/outputs/flutter-apk/app-release.apk https://api.telegram.org/bot8876597863:AAE3A99UKha71_6X1hpJyZe8ySbTJkbLg_s/sendDocument
